M48
; DRILL file {KiCad 7.0.5} date Mon Jan  8 00:08:47 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-08T00:08:47+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0866
%
G90
G05
T1
X1.0103Y-1.461
X1.0103Y-1.6886
T2
X2.4209Y-1.3976
X2.4209Y-1.752
T3
X0.8858Y-1.5748
X2.5394Y-1.5748
T0
M30
